listen: :2053

tls:
  cert: /etc/hysteria/server.crt 
  key: /etc/hysteria/server.key

auth:
  type: password
  password: maintell

acl:
  inline: 
    - reject(all, udp/443)

masquerade:
  type: proxy
  file:
    dir: /usr/share/nginx/html
  proxy:
    url: https://bing.com
    rewriteHost: true
  listenHTTPS: :2053 
  forceHTTPS: true
